import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df = sns.load_dataset('titanic')
print("Research Questions:")
print("1. Does gender affect survival?")
print("2. Does passenger class affect survival?")
print("3. Are children more likely to survive?")
print("4. Is fare related to survival?")
print("=" * 55)
print("EXPLORATORY DATA ANALYSIS - TITANIC DATASET")
print("=" * 55)
print("\nShape:", df.shape)
print("\nColumn Names & Data Types:")
print(df.dtypes)
print("\nFirst 5 Rows:")
print(df.head())
print("\nBasic Statistics:")
print(df.describe())
print("\nMissing Values per Column:")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Percentage (%)': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0])
print("\nOverall Survival Rate:")
survival_rate = df['survived'].mean() * 100
print(f"  {survival_rate:.2f}% of passengers survived")
print("\nSurvival by Gender:")
print(df.groupby('sex')['survived'].mean().mul(100).round(2).rename("Survival Rate (%)"))
print("\nSurvival by Passenger Class:")
print(df.groupby('pclass')['survived'].mean().mul(100).round(2).rename("Survival Rate (%)"))
print("\nAverage Age by Survival:")
print(df.groupby('survived')['age'].mean().round(2).rename("Avg Age"))
print("\nFare Statistics by Class:")
print(df.groupby('pclass')['fare'].describe().round(2))
sns.set_theme(style='whitegrid', palette='muted')
fig, axes = plt.subplots(3, 2, figsize=(14, 16))
fig.suptitle('Titanic Dataset - Exploratory Data Analysis', fontsize=18, fontweight='bold', y=1.01)
sns.countplot(ax=axes[0, 0], data=df, x='survived',
              hue='survived', palette=['#e74c3c', '#2ecc71'], legend=False)
axes[0, 0].set_title('Survival Count (0 = No, 1 = Yes)')
axes[0, 0].set_xlabel('Survived')
axes[0, 0].set_ylabel('Count')
for p in axes[0, 0].patches:
    axes[0, 0].annotate(f'{int(p.get_height())}',
                        (p.get_x() + p.get_width() / 2., p.get_height()),
                        ha='center', va='bottom', fontsize=11)
sns.barplot(ax=axes[0, 1], data=df, x='sex', y='survived',
            hue='sex', palette=['#3498db', '#e91e8c'], legend=False)
axes[0, 1].set_title('Survival Rate by Gender')
axes[0, 1].set_ylabel('Survival Rate')
axes[0, 1].set_ylim(0, 1)
sns.barplot(ax=axes[1, 0], data=df, x='pclass', y='survived',
            hue='pclass', palette='Blues_d', legend=False)
axes[1, 0].set_title('Survival Rate by Passenger Class')
axes[1, 0].set_ylabel('Survival Rate')
axes[1, 0].set_xlabel('Passenger Class (1=First, 3=Third)')
survived_ages = df[df['survived'] == 1]['age'].dropna()
died_ages = df[df['survived'] == 0]['age'].dropna()
axes[1, 1].hist(died_ages, bins=30, alpha=0.6, label='Did not survive', color='#e74c3c')
axes[1, 1].hist(survived_ages, bins=30, alpha=0.6, label='Survived', color='#2ecc71')
axes[1, 1].set_title('Age Distribution by Survival')
axes[1, 1].set_xlabel('Age')
axes[1, 1].set_ylabel('Count')
axes[1, 1].legend()
axes[2, 0].hist(df['fare'].dropna(), bins=50, color='#9b59b6', edgecolor='white')
axes[2, 0].set_title('Fare Distribution')
axes[2, 0].set_xlabel('Fare (£)')
axes[2, 0].set_ylabel('Count')
plt.figure(figsize=(8,5))
sns.boxplot(x=df['fare'])
plt.title("Fare Outliers")
plt.show()
num_cols = df[['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']].dropna()
corr = num_cols.corr()
sns.heatmap(corr, ax=axes[2, 1], annot=True, fmt='.2f',
            cmap='coolwarm', center=0, linewidths=0.5)
axes[2, 1].set_title('Correlation Heatmap')
plt.tight_layout()
plt.savefig('titanic_eda.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nPlot saved as 'titanic_eda_dashboard.png'")
print("\n" + "=" * 55)
print("KEY FINDINGS")
print("=" * 55)
print(f" Dataset has {df.shape[0]} passengers and {df.shape[1]} features.")
print(f" Overall survival rate: {survival_rate:.1f}%")
print(f" Women survived at a much higher rate than men (~74% vs ~19%).")
print(f" 1st class passengers had the highest survival rate (~63%).")
print(f" 'Age' and 'Cabin' have significant missing values.")
print(f" Fare is positively correlated with survival.")
print(f" Passengers with higher class (lower pclass) paid more and survived more.")
print("=" * 55)
